### ISSUE TITLE
Pipeline between Train and Optimize task are not connected

### ISSUE THREAD

**Issue by yamasakih** [m3dev/redshells#48]
Hi,

Thanks for presenting examples of important tasks in machine learning, OptimizeTask and TrainTask.
I want to know how I can all task by running only TrainTask in below code.

https://github.com/yamasakih/redshells/blob/feature/add-thunderbolt-example/examples/thunderbolt_example.py

This code is based on the following site.  
https://github.com/vaaaaanquish/gokart_redshells_thunderbolt_example/blob/master/Example.ipynb

When I ran TrainTask, gokart raised below error.

```python
[2019-11-12 22:08:40,934][WARNING](worker.py:658) Will not run sample.TrainXGBoostModel(n_estimators=50, test_size=0.2) or any dependencies due to error in complete() method:
Traceback (most recent call last):
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/luigi/worker.py", line 409, in check_complete
    is_complete = task.complete()
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/gokart/task.py", line 69, in complete
    is_completed = all([t.exists() for t in luigi.task.flatten(self.output())])
  File "thunderbolt_example.py", line 104, in output
    return self.make_target('TrainXGBoostModel.pkl')
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/gokart/task.py", line 102, in make_target
    unique_id = self.make_unique_id() if use_unique_id else None
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/gokart/task.py", line 182, in make_unique_id
    self.task_unique_id = self.task_unique_id or self._make_hash_id()
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/gokart/task.py", line 191, in _make_hash_id
    dependencies = [_to_str_params(task) for task in luigi.task.flatten(self.requires())]
  File "thunderbolt_example.py", line 93, in requires
    param = self.clone(OptimizeXGBoostModel).load()
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/gokart/task.py", line 146, in load
    return _load(self._get_input_targets(target))
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/gokart/task.py", line 144, in _load
    return targets.load()
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/gokart/target.py", line 58, in load
    with self._target.open('r') as f:
  File "/Users/yamasakih/anaconda3/envs/gokart/lib/python3.7/site-packages/luigi/local_target.py", line 165, in open
    fileobj = FileWrapper(io.BufferedReader(io.FileIO(self.path, mode)))
FileNotFoundError: [Errno 2] No such file or directory: './resources/model/OptimizeXGBoostModel_c3153844698935b3eb1eb42d91e218fb.pkl'
```

So, I have to run OptimizeTask, and next run TrainTask. It takes a little time :(

I'd like you to tell me if better coding works.  Thank you in advance!

**Comment by vaaaaanquish** [comment]
@yamasakih 

Hi. Please try this code.
```
def requires(self)
        param = OptimizeXGBoostModel().output().load()
        return redshells.train.TrainClassificationModel(
            rerun=True,
            train_data_task=data,
            target_column_name='target',
            model_name='XGBClassifier',
            model_kwargs=param['best_params']
        )
```

**Comment by vaaaaanquish** [comment]
@yamasakih Hi. Thanks.

Please try this code.
```
        task = TrainOptimizeXGB()
        if not task.complete():
            task.run()
        param = task.output().load()
```

**Comment by vaaaaanquish** [comment]
@yamasakih Hi. Thanks issue.

Please try this code.
```
    def requires(self):
        data = MakeData()
        task = TrainOptimizeXGB()
        if not task.complete():
            luigi.build([task], local_scheduler=True)
        param = task.output().load()
        return redshells.train.TrainClassificationModel(rerun=True,
                                                        train_data_task=data,
                                                        target_column_name='author',
                                                        model_name='XGBClassifier',
                                                        model_kwargs=param['best_params'])
```

**Comment by yamasakih** [comment]
@vaaaaanquish  

Thx, your comment.

It worked well :) We were able to run together!!
Thank you very much!
